# SPDX-License-Identifier: MPL-2.0
if(NOT DEFINED ANOSECUREKIT_WORKFLOW_FILE)
  set(ANOSECUREKIT_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/anosecurekit-ci.yml")
endif()

if(NOT DEFINED ANOSECUREKIT_CODEQL_WORKFLOW_FILE)
  set(ANOSECUREKIT_CODEQL_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/codeql.yml")
endif()

if(NOT DEFINED ANOSECUREKIT_FUZZ_WORKFLOW_FILE)
  set(ANOSECUREKIT_FUZZ_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/fuzz.yml")
endif()

if(NOT EXISTS "${ANOSECUREKIT_WORKFLOW_FILE}")
  message(FATAL_ERROR "Workflow file not found: ${ANOSECUREKIT_WORKFLOW_FILE}")
endif()

if(NOT EXISTS "${ANOSECUREKIT_CODEQL_WORKFLOW_FILE}")
  message(FATAL_ERROR "CodeQL workflow file not found: ${ANOSECUREKIT_CODEQL_WORKFLOW_FILE}")
endif()

if(NOT EXISTS "${ANOSECUREKIT_FUZZ_WORKFLOW_FILE}")
  message(FATAL_ERROR "Fuzz workflow file not found: ${ANOSECUREKIT_FUZZ_WORKFLOW_FILE}")
endif()

file(READ "${ANOSECUREKIT_WORKFLOW_FILE}" _anosecurekit_workflow)
file(READ "${ANOSECUREKIT_CODEQL_WORKFLOW_FILE}" _anosecurekit_codeql_workflow)
file(READ "${ANOSECUREKIT_FUZZ_WORKFLOW_FILE}" _anosecurekit_fuzz_workflow)
string(REPLACE "\r\n" "\n" _anosecurekit_workflow "${_anosecurekit_workflow}")
string(REPLACE "\r" "\n" _anosecurekit_workflow "${_anosecurekit_workflow}")
string(REPLACE "\r\n" "\n" _anosecurekit_codeql_workflow "${_anosecurekit_codeql_workflow}")
string(REPLACE "\r" "\n" _anosecurekit_codeql_workflow "${_anosecurekit_codeql_workflow}")
string(REPLACE "\r\n" "\n" _anosecurekit_fuzz_workflow "${_anosecurekit_fuzz_workflow}")
string(REPLACE "\r" "\n" _anosecurekit_fuzz_workflow "${_anosecurekit_fuzz_workflow}")

function(_anosecurekit_require_workflow_text description needle)
  string(FIND "${_anosecurekit_workflow}" "${needle}" _anosecurekit_found_at)
  if(_anosecurekit_found_at EQUAL -1)
    message(FATAL_ERROR "Workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_anosecurekit_require_codeql_text description needle)
  string(FIND "${_anosecurekit_codeql_workflow}" "${needle}" _anosecurekit_found_at)
  if(_anosecurekit_found_at EQUAL -1)
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_anosecurekit_require_codeql_regex description pattern)
  string(REGEX MATCH "${pattern}" _anosecurekit_match "${_anosecurekit_codeql_workflow}")
  if(_anosecurekit_match STREQUAL "")
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${pattern}")
  endif()
endfunction()

function(_anosecurekit_require_fuzz_text description needle)
  string(FIND "${_anosecurekit_fuzz_workflow}" "${needle}" _anosecurekit_found_at)
  if(_anosecurekit_found_at EQUAL -1)
    message(FATAL_ERROR "Fuzz workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_anosecurekit_require_fuzz_regex description pattern)
  string(REGEX MATCH "${pattern}" _anosecurekit_match "${_anosecurekit_fuzz_workflow}")
  if(_anosecurekit_match STREQUAL "")
    message(FATAL_ERROR "Fuzz workflow missing ${description}: ${pattern}")
  endif()
endfunction()

_anosecurekit_require_workflow_text("tag trigger" "tags:")
_anosecurekit_require_workflow_text("v tag pattern" "- 'v*'")
_anosecurekit_require_workflow_text("default read-only token permission" "permissions:\n  contents: read")
_anosecurekit_require_workflow_text("release job" "release:")
_anosecurekit_require_workflow_text("release dependency on build matrix" "needs: [build, install-only, linux-static, windows-shared, linux-sanitizers, macos-package]")
_anosecurekit_require_workflow_text("release tag guard" "startsWith(github.ref, 'refs/tags/v')")
_anosecurekit_require_workflow_text("release write token permission" "permissions:\n      contents: write")
_anosecurekit_require_workflow_text("release OIDC token permission" "id-token: write")
_anosecurekit_require_workflow_text("release attestation permission" "attestations: write")
_anosecurekit_require_workflow_text("current checkout action" "uses: actions/checkout@v7")
_anosecurekit_require_workflow_text("current cache action" "uses: actions/cache@v6")
_anosecurekit_require_workflow_text("current upload artifact action" "uses: actions/upload-artifact@v7")
_anosecurekit_require_workflow_text("warnings as errors CI option" "-DANOSECUREKIT_WARNINGS_AS_ERRORS=ON")
_anosecurekit_require_workflow_text("Linux sanitizer job" "linux-sanitizers:")
_anosecurekit_require_workflow_text("Linux sanitizer name" "ubuntu-latest clang Debug sanitizers")
_anosecurekit_require_workflow_text("address sanitizer flag" "-fsanitize=address,undefined")
_anosecurekit_require_workflow_text("sanitizer check target" "cmake --build build --config Debug --target check")
_anosecurekit_require_workflow_text("macOS package job" "macos-package:")
_anosecurekit_require_workflow_text("macOS job name" "macos-latest appleclang Release package")
_anosecurekit_require_workflow_text("macOS OpenSSL dependency" "brew install ninja openssl@3")
_anosecurekit_require_workflow_text("macOS OpenSSL root" "-DOPENSSL_ROOT_DIR=\"\$(brew --prefix openssl@3)\"")
_anosecurekit_require_workflow_text("macOS package target" "cmake --build build --config Release --target package-check")
_anosecurekit_require_workflow_text("matrix package artifact" "anosecurekit-\${{ matrix.os }}-\${{ matrix.compiler }}-\${{ matrix.build_type }}-packages")
_anosecurekit_require_workflow_text("install-only package artifact" "anosecurekit-ubuntu-gcc-release-install-only-packages")
_anosecurekit_require_workflow_text("Linux static package artifact" "anosecurekit-ubuntu-gcc-release-static-packages")
_anosecurekit_require_workflow_text("Windows shared package artifact" "anosecurekit-windows-msvc-release-shared-packages")
_anosecurekit_require_workflow_text("macOS package artifact" "anosecurekit-macos-clang-release-packages")
_anosecurekit_require_workflow_text("release artifact download" "uses: actions/download-artifact@v8")
_anosecurekit_require_workflow_text("package artifact ZIP upload filter" "build/package-check/artifacts/*.zip")
_anosecurekit_require_workflow_text("package artifact TGZ upload filter" "build/package-check/artifacts/*.tar.gz")
_anosecurekit_require_workflow_text("release tag version extraction" "tag_version=\"\${GITHUB_REF_NAME#v}\"")
_anosecurekit_require_workflow_text("release asset ZIP glob" "release-artifacts/*/anosecurekit-\"\$tag_version\"-*.zip")
_anosecurekit_require_workflow_text("release asset TGZ glob" "release-artifacts/*/anosecurekit-\"\$tag_version\"-*.tar.gz")
_anosecurekit_require_workflow_text("release artifact version guard" "Release artifact version does not match tag")
_anosecurekit_require_workflow_text("release SemVer tag guard" "Release tag is not SemVer")
_anosecurekit_require_workflow_text("release binary artifact prefix" "dist/\${artifact_name}-\${base}")
_anosecurekit_require_workflow_text("release source artifact de-duplication" "copied_source")
_anosecurekit_require_workflow_text("release source ZIP requirement" "expected_source_zip=\"anosecurekit-\${tag_version}-source.zip\"")
_anosecurekit_require_workflow_text("release source TGZ requirement" "expected_source_tgz=\"anosecurekit-\${tag_version}-source.tar.gz\"")
_anosecurekit_require_workflow_text("release expected binary artifact list" "expected_binary_artifacts=(")
_anosecurekit_require_workflow_text("release expected GCC Release binary artifact" "\"anosecurekit-ubuntu-latest-gcc-Release-packages\"")
_anosecurekit_require_workflow_text("release expected Clang Release binary artifact" "\"anosecurekit-ubuntu-latest-clang-Release-packages\"")
_anosecurekit_require_workflow_text("release expected GCC Debug binary artifact" "\"anosecurekit-ubuntu-latest-gcc-Debug-packages\"")
_anosecurekit_require_workflow_text("release expected MSVC Release binary artifact" "\"anosecurekit-windows-latest-msvc-Release-packages\"")
_anosecurekit_require_workflow_text("release expected install-only binary artifact" "\"anosecurekit-ubuntu-gcc-release-install-only-packages\"")
_anosecurekit_require_workflow_text("release expected static binary artifact" "\"anosecurekit-ubuntu-gcc-release-static-packages\"")
_anosecurekit_require_workflow_text("release expected shared binary artifact" "\"anosecurekit-windows-msvc-release-shared-packages\"")
_anosecurekit_require_workflow_text("release expected macOS binary artifact" "\"anosecurekit-macos-clang-release-packages\"")
_anosecurekit_require_workflow_text("release expected binary suffix list" "expected_binary_suffixes=(\".zip\" \".tar.gz\")")
_anosecurekit_require_workflow_text("release source ZIP guard" "No source ZIP package artifact found")
_anosecurekit_require_workflow_text("release source TGZ guard" "No source TGZ package artifact found")
_anosecurekit_require_workflow_text("release binary artifact guard" "No binary \$expected_binary_suffix package artifact found for")
_anosecurekit_require_workflow_text("release SBOM file name" "sbom_name=\"anosecurekit-\${tag_version}-release.spdx.json\"")
_anosecurekit_require_workflow_text("release SBOM generation step" "- name: Generate release SBOM")
_anosecurekit_require_workflow_text("release SBOM SPDX version" "spdxVersion")
_anosecurekit_require_workflow_text("release checksum generation" "sha256sum")
_anosecurekit_require_workflow_text("release checksum file" "SHA256SUMS.txt")
_anosecurekit_require_workflow_text("release artifact attestation action" "uses: actions/attest-build-provenance@v4")
_anosecurekit_require_workflow_text("release artifact attestation subject" "subject-path: dist/*")
_anosecurekit_require_workflow_text("release artifact download step" "- name: Download package artifacts")
_anosecurekit_require_workflow_text("release view explicit repo" "gh release view \"$tag\" --repo \"$GITHUB_REPOSITORY\"")
_anosecurekit_require_workflow_text("Community release title" "title=\"AnoSecureKit Community \${tag}\"")
_anosecurekit_require_workflow_text("release edit explicit repo" "gh release edit \"$tag\" --repo \"$GITHUB_REPOSITORY\" --title \"$title\"")
_anosecurekit_require_workflow_text("release create generated notes" "gh release create \"$tag\" --repo \"$GITHUB_REPOSITORY\" --verify-tag --title \"$title\" --generate-notes")
_anosecurekit_require_workflow_text("release creation" "gh release create")
_anosecurekit_require_workflow_text("release asset upload explicit repo" "gh release upload \"$GITHUB_REF_NAME\" --repo \"$GITHUB_REPOSITORY\"")

_anosecurekit_require_codeql_text("workflow name" "name: \"CodeQL\"")
_anosecurekit_require_codeql_regex("main push trigger" "push:[\r\n]+    branches: \\[ \"main\" \\]")
_anosecurekit_require_codeql_regex("main pull request trigger" "pull_request:[\r\n]+    branches: \\[ \"main\" \\]")
_anosecurekit_require_codeql_regex("scheduled analysis" "schedule:[\r\n]+    - cron:")
_anosecurekit_require_codeql_text("current checkout action" "uses: actions/checkout@v7")
_anosecurekit_require_codeql_text("current CodeQL init action" "uses: github/codeql-action/init@v4")
_anosecurekit_require_codeql_text("manual CodeQL build mode" "build-mode: manual")
_anosecurekit_require_codeql_text("manual CMake configure" "cmake -S . -B build-codeql")
_anosecurekit_require_codeql_text("manual CMake build" "cmake --build build-codeql --config Release")
_anosecurekit_require_codeql_text("current CodeQL analyze action" "uses: github/codeql-action/analyze@v4")

_anosecurekit_require_fuzz_text("workflow name" "name: Fuzz")
_anosecurekit_require_fuzz_regex("weekly schedule" "schedule:[\r\n]+    - cron:")
_anosecurekit_require_fuzz_text("manual dispatch" "workflow_dispatch:")
_anosecurekit_require_fuzz_text("read-only token permission" "permissions:\n  contents: read")
_anosecurekit_require_fuzz_text("checkout action" "uses: actions/checkout@v7")
_anosecurekit_require_fuzz_text("Linux fuzz dependencies" "sudo apt-get update && sudo apt-get install -y clang libssl-dev ninja-build")
_anosecurekit_require_fuzz_text("fuzz CMake option" "-DANOSECUREKIT_BUILD_FUZZ=ON")
_anosecurekit_require_fuzz_text("tests disabled" "-DANOSECUREKIT_BUILD_TESTS=OFF")
_anosecurekit_require_fuzz_text("CLI build disabled" "-DANOSECUREKIT_BUILD_CLI=OFF")
_anosecurekit_require_fuzz_text("fuzz-smoke target" "cmake --build build-fuzz --target fuzz-smoke")
_anosecurekit_require_fuzz_text("job timeout" "timeout-minutes: 30")
_anosecurekit_require_fuzz_text("target runtime limit" "-max_total_time=60")
_anosecurekit_require_fuzz_text("crash artifact directory" "fuzz-artifacts")
_anosecurekit_require_fuzz_text("artifact retention" "retention-days: 7")
_anosecurekit_require_fuzz_text("artifact upload action" "uses: actions/upload-artifact@v7")
