# SPDX-License-Identifier: MPL-2.0
foreach(required IN ITEMS
    ANOSECUREKIT_SOURCE_DIR
    ANOSECUREKIT_CHECK_ROOT
    ANOSECUREKIT_PROJECT_VERSION
    ANOSECUREKIT_PROJECT_VERSION_MAJOR
    ANOSECUREKIT_PROJECT_VERSION_MINOR
    ANOSECUREKIT_PROJECT_VERSION_PATCH)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

if(NOT DEFINED ANOSECUREKIT_BUILD_CONFIG OR ANOSECUREKIT_BUILD_CONFIG STREQUAL "")
  if(DEFINED ANOSECUREKIT_DEFAULT_BUILD_TYPE AND NOT ANOSECUREKIT_DEFAULT_BUILD_TYPE STREQUAL "")
    set(ANOSECUREKIT_BUILD_CONFIG "${ANOSECUREKIT_DEFAULT_BUILD_TYPE}")
  else()
    set(ANOSECUREKIT_BUILD_CONFIG Release)
  endif()
endif()

set(build_dir "${ANOSECUREKIT_CHECK_ROOT}/build")
set(install_dir "${ANOSECUREKIT_CHECK_ROOT}/install")
set(consumer_dir "${ANOSECUREKIT_CHECK_ROOT}/consumer")
file(REMOVE_RECURSE "${ANOSECUREKIT_CHECK_ROOT}")
file(MAKE_DIRECTORY "${ANOSECUREKIT_CHECK_ROOT}")

set(configure_args
  -S "${ANOSECUREKIT_SOURCE_DIR}"
  -B "${build_dir}"
  -DBUILD_SHARED_LIBS=ON
  -DANOSECUREKIT_BUILD_TESTS=OFF
  -DANOSECUREKIT_BUILD_CLI=OFF
  -DANOSECUREKIT_INSTALL_CLI=OFF
  -DANOSECUREKIT_CRYPTO_BACKEND=openssl
  -DCMAKE_BUILD_TYPE=${ANOSECUREKIT_BUILD_CONFIG})
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR AND NOT ANOSECUREKIT_CMAKE_GENERATOR STREQUAL "")
  list(APPEND configure_args -G "${ANOSECUREKIT_CMAKE_GENERATOR}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM AND NOT ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM STREQUAL "")
  list(APPEND configure_args -A "${ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET AND NOT ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET STREQUAL "")
  list(APPEND configure_args -T "${ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_MAKE_PROGRAM AND NOT ANOSECUREKIT_CMAKE_MAKE_PROGRAM STREQUAL "")
  list(APPEND configure_args -DCMAKE_MAKE_PROGRAM=${ANOSECUREKIT_CMAKE_MAKE_PROGRAM})
endif()
if(DEFINED ANOSECUREKIT_CMAKE_CXX_COMPILER AND NOT ANOSECUREKIT_CMAKE_CXX_COMPILER STREQUAL "")
  list(APPEND configure_args -DCMAKE_CXX_COMPILER=${ANOSECUREKIT_CMAKE_CXX_COMPILER})
endif()
if(DEFINED OPENSSL_ROOT_DIR AND NOT OPENSSL_ROOT_DIR STREQUAL "")
  list(APPEND configure_args -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR})
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_args} RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared package configure failed")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${build_dir}" --config "${ANOSECUREKIT_BUILD_CONFIG}" --target shared-symbol-check
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared symbol check failed")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" --install "${build_dir}" --config "${ANOSECUREKIT_BUILD_CONFIG}" --prefix "${install_dir}"
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared package install failed")
endif()

set(consumer_args
  -S "${ANOSECUREKIT_SOURCE_DIR}/tests/consumer"
  -B "${consumer_dir}"
  -DCMAKE_PREFIX_PATH=${install_dir}
  -DCMAKE_BUILD_TYPE=${ANOSECUREKIT_BUILD_CONFIG}
  -DANOSECUREKIT_EXPECTED_VERSION=${ANOSECUREKIT_PROJECT_VERSION}
  -DANOSECUREKIT_EXPECTED_VERSION_MAJOR=${ANOSECUREKIT_PROJECT_VERSION_MAJOR}
  -DANOSECUREKIT_EXPECTED_VERSION_MINOR=${ANOSECUREKIT_PROJECT_VERSION_MINOR}
  -DANOSECUREKIT_EXPECTED_VERSION_PATCH=${ANOSECUREKIT_PROJECT_VERSION_PATCH})
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR AND NOT ANOSECUREKIT_CMAKE_GENERATOR STREQUAL "")
  list(APPEND consumer_args -G "${ANOSECUREKIT_CMAKE_GENERATOR}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM AND NOT ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM STREQUAL "")
  list(APPEND consumer_args -A "${ANOSECUREKIT_CMAKE_GENERATOR_PLATFORM}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET AND NOT ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET STREQUAL "")
  list(APPEND consumer_args -T "${ANOSECUREKIT_CMAKE_GENERATOR_TOOLSET}")
endif()
if(DEFINED ANOSECUREKIT_CMAKE_MAKE_PROGRAM AND NOT ANOSECUREKIT_CMAKE_MAKE_PROGRAM STREQUAL "")
  list(APPEND consumer_args -DCMAKE_MAKE_PROGRAM=${ANOSECUREKIT_CMAKE_MAKE_PROGRAM})
endif()
if(DEFINED ANOSECUREKIT_CMAKE_CXX_COMPILER AND NOT ANOSECUREKIT_CMAKE_CXX_COMPILER STREQUAL "")
  list(APPEND consumer_args -DCMAKE_CXX_COMPILER=${ANOSECUREKIT_CMAKE_CXX_COMPILER})
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" ${consumer_args} RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared installed consumer configure failed")
endif()
execute_process(
  COMMAND "${CMAKE_COMMAND}" --build "${consumer_dir}" --config "${ANOSECUREKIT_BUILD_CONFIG}"
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared installed consumer build failed")
endif()

if(WIN32)
  set(exe "${consumer_dir}/${ANOSECUREKIT_BUILD_CONFIG}/anosecurekit_consumer.exe")
  if(NOT EXISTS "${exe}")
    set(exe "${consumer_dir}/anosecurekit_consumer.exe")
  endif()
  set(runtime_path "${install_dir}/bin")
  if(DEFINED ANOSECUREKIT_OPENSSL_RUNTIME_DIR AND NOT ANOSECUREKIT_OPENSSL_RUNTIME_DIR STREQUAL "")
    set(runtime_path "${runtime_path};${ANOSECUREKIT_OPENSSL_RUNTIME_DIR}")
  endif()
  set(runtime_path "${runtime_path};$ENV{PATH}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PATH=${runtime_path}" "${exe}" RESULT_VARIABLE result)
elseif(APPLE)
  set(exe "${consumer_dir}/anosecurekit_consumer")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "DYLD_LIBRARY_PATH=${install_dir}/lib:$ENV{DYLD_LIBRARY_PATH}" "${exe}" RESULT_VARIABLE result)
else()
  set(exe "${consumer_dir}/anosecurekit_consumer")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "LD_LIBRARY_PATH=${install_dir}/lib:$ENV{LD_LIBRARY_PATH}" "${exe}" RESULT_VARIABLE result)
endif()
if(NOT result EQUAL 0)
  message(FATAL_ERROR "shared installed consumer run failed")
endif()

message(STATUS "AnoSecureKit shared package and symbol check passed")
